# Generated by Django 5.2.16 on 2026-08-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=32, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=64)),
                ('device_type', models.CharField(blank=True, max_length=48)),
                ('site', models.CharField(blank=True, max_length=48)),
                ('ise_identity_group', models.CharField(blank=True, max_length=64)),
                ('ise_profile', models.CharField(blank=True, max_length=64)),
                ('correlation', models.CharField(blank=True, max_length=32)),
                ('ise_endpoint_mac', models.CharField(blank=True, max_length=32)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(db_index=True, max_length=16)),
                ('site', models.CharField(blank=True, db_index=True, max_length=48)),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=48)),
                ('events', models.IntegerField(default=0)),
                ('threats', models.IntegerField(default=0)),
                ('critical', models.IntegerField(default=0)),
                ('blocked', models.IntegerField(default=0)),
                ('allowed', models.IntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('devices', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['hour', 'site', 'device_type'], name='dashboard_h_hour_171f4c_idx')],
                'unique_together': {('hour', 'site', 'device_type')},
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('hour', models.CharField(db_index=True, max_length=16)),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('severity', models.CharField(db_index=True, max_length=16)),
                ('impact', models.IntegerField(default=0)),
                ('device_mac', models.CharField(db_index=True, max_length=32)),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=48)),
                ('hostname', models.CharField(blank=True, max_length=64)),
                ('site', models.CharField(blank=True, db_index=True, max_length=48)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('in_ise', models.BooleanField(default=False)),
                ('mapped_ise_mac', models.CharField(blank=True, max_length=32)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dest_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dest_country', models.CharField(blank=True, max_length=48)),
                ('application', models.CharField(blank=True, max_length=48)),
                ('protocol', models.CharField(blank=True, max_length=16)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('insecure_protocol', models.BooleanField(default=False)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('action', models.CharField(blank=True, max_length=24)),
                ('rule_matched', models.CharField(blank=True, max_length=128)),
                ('ips_policy', models.CharField(blank=True, max_length=128)),
                ('src_zone', models.CharField(blank=True, max_length=64)),
                ('dst_zone', models.CharField(blank=True, max_length=64)),
                ('firewall', models.CharField(blank=True, max_length=128)),
                ('threat_name', models.CharField(blank=True, max_length=256)),
                ('threat_category', models.CharField(blank=True, max_length=128)),
                ('classtype', models.CharField(blank=True, max_length=64)),
                ('zone_violation', models.BooleanField(default=False)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['ts', 'event_type'], name='dashboard_s_ts_785509_idx'), models.Index(fields=['device_type', 'site'], name='dashboard_s_device__5636d7_idx'), models.Index(fields=['device_mac', 'ts'], name='dashboard_s_device__e8d3d3_idx')],
            },
        ),
    ]
