# Generated by Django 6.1 on 2026-08-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
